### ISSUE TITLE
"nios_next_network.py" lookup module does not support IPv6

### ISSUE THREAD

**Issue by Courby** [infobloxopen/infoblox-ansible#133]
The current version of nios_next_network.py lookup module does not support IPv6 lookup. 
I.e. when trying to use from Ansible like this:
```
    - name: return next available Network from 2001:1:111:1::0/64    
      set_fact:    
        ip6net: "{{ lookup('infoblox.nios_modules.nios_next_network', '2001:1:111:1::0/64', cidr=126, provider=nios_provider) }}" 
```
it fails.

**Comment by JkhatriInfobox** [comment]
Hi @Courby,

PR #178 has resolved this issue, so we are closing it. If the issue persists, please feel free to reopen it or create a new one.

Thank you!
