### ISSUE TITLE
feat: support DTC health monitors

### ISSUE THREAD

**Issue by jbisabel** [infobloxopen/infoblox-ansible#189]
The current nios_dtc_pool module allows you to attach existing monitors to a DTC pool, however currently there is no module that allows you to actually create/manage monitors

**Comment by badnetmask** [comment]
Just like #190 , I did not have that use-case in my environment when I wrote this module, because we use monitors on the member level, instead of the pool. I will try to find some time to look into it as well.

**Comment by badnetmask** [comment]
@jbisabel @JkhatriInfobox - Since #191 has been merged, does it mean this issue can be closed? (I don't have access to do so).

**Comment by JkhatriInfobox** [comment]
@jbisabel - Thanks for update, will close the issue.

As DTC health monitors are supported by #191
