### ISSUE TITLE
bug: DTC topology

### ISSUE THREAD

**Issue by jbisabel** [infobloxopen/infoblox-ansible#190]
The nios_dtc_pool and nios_dtc_lbdn modules currently allow to choose `TOPOLOGY` as `lb_preferred_method` and `lb_method`. However specifying this errors out because you can't pass the actual topology that the pool/lbdn should use (nor is there a module that allows you to create them in the first place)

**Comment by badnetmask** [comment]
@jbisabel when I wrote these modules I didn't have a use-case for topology, so I did not realize it required some extra parameters. I will find some time to add this.

Quick question though: would you have any expectations to actually define the topology itself from Ansible, or simply referring to it from the pool/lbdn would be enough for you?

**Comment by jbisabel** [comment]
@badnetmask Ideally there'd also be a separate module allowing me to actually define the topologies as well. As you maybe saw, I created a separate similar feature request for monitors as well.

**Comment by ranjishmp** [comment]
@hemanthKa677 Please review this PR

**Comment by praig** [comment]
Same issue. Same response to topology question as well.

**Comment by badnetmask** [comment]
@JkhatriInfobox - Since #191 has been merged, does it mean this issue can be closed? (I don't have access to do so).

**Comment by JkhatriInfobox** [comment]
Closing this issue as #191 has been merged. Thanks to everyone involved!
