### ISSUE TITLE
max_results uses the INFOBLOX_MAX_RETRIES environment variable

### ISSUE THREAD

**Issue by dthomson-triumf** [infobloxopen/infoblox-ansible#198]
See:

https://github.com/infobloxopen/infoblox-ansible/blob/b0401ab535e56f14ec8329a0fdae3c54369245d6/plugins/module_utils/api.py#L88C4-L88C4

This should be `INFOBLOX_MAX_RESULTS` or something like that.

**Comment by dthomson-triumf** [comment]
While I'm at it: https://github.com/infobloxopen/infoblox-ansible/blob/master/plugins/module_utils/api.py#L87C92-L87C92 looks like it should probably be using `INFOBLOX_WAPI_VERSION` not `INFOBLOX_WAP_VERSION`.

**Comment by JkhatriInfobox** [comment]
As env variable for max_result is fixed in PR #209 has been merged and released.

Therefore, we are closing this issue. If the problem persists, please feel free to reopen it or create a new issue."
