### ISSUE TITLE
Add range option to next_ip option

### ISSUE THREAD

**Issue by machacekondra** [infobloxopen/infoblox-ansible#199]
Since `next_available_ip` plugin finds free IP from network excluding the DHCP range. It would be nice to have option also to return free IP from DHCP range.

**Comment by evilhamsterman** [comment]
Why would you want to do that? Static IPs should not come from your dynamic IP pool.

**Comment by machacekondra** [comment]
Yeah, this issue is about getting first available IP from dynamic pool not static. Getting IP from static pool works fine.

**Comment by evilhamsterman** [comment]
I understand that, but why would you want to do that? If you want an IP from the dynamic pool you use DHCP. It's bad practice to assign static IPs from the DHCP pool.

If you want to statically assign an IP to a device but have the device get that IP address from DHCP you assign it an IP outside the dynamic pool and just enable the address for DHCP.

**Comment by machacekondra** [comment]
Well, my flow is as follows:
1) Request IP
2) Create DNS record
3) Boot my machine using DHCP
4) Get machine's MAC address
5) Reserve the IP in DHCP for the MAC address.

So you suggest to request IP from non-dynamic pool and later add it to DHCP pool?
