### ISSUE TITLE
galaxy.yml points to a non existent tag

### ISSUE THREAD

**Issue by ajmt-dev** [infobloxopen/infoblox-ansible#208]
On master it's pointing to a non-existent tag which is breaking my ansible-builder from resolving dependencies: 

https://github.com/infobloxopen/infoblox-ansible/blob/5a7577babc08251ec50056625d9e8d278c833a5b/galaxy.yml#L12

Can this be amended back to 1.5.0 or the relevant Tag created?

Thanks,
Andy

**Comment by JkhatriInfobox** [comment]
As our previous release contains the Tag 1.6.0 and latest as 1.70. seems issue is no longer persists.

Therefore, we are closing this issue. If the problem persists, please feel free to reopen it or create a new issue."
