### ISSUE TITLE
Inclusion in Ansible 2.10.x

### ISSUE THREAD

**Issue by felixfontein** [infobloxopen/infoblox-ansible#24]
I was looking at this collection a bit. Here's what I noticed.

New content:
 - inventory plugin

Things to look at:
 - inventory plugin needs FQCN tag (`plugin` option)
 - using version_added with bad version numbers (inventory plugin)
 - lookup examples need FQCN

Questions:
 - are integration tests run somewhere?
 - is https://github.com/infobloxopen/infoblox-ansible/tree/master/obsolete still needed?

Besides that, LGTM.

CC @gundalow @abadger

**Comment by Vaishnavi-infoblox** [comment]
Hi Felix,

Please find my below answers.

- are integration tests run somewhere?
   We have moved all our code and integration tests to https://github.com/infobloxopen/infoblox-ansible

- is https://github.com/infobloxopen/infoblox-ansible/tree/master/obsolete still needed?
  This is not required now.

**Comment by felixfontein** [comment]
Hi @Vaishnavi-infoblox, thanks for your answers!

About integration tests: I'm more wondering whether you are actually running the integration tests in CI somewhere. They are not run in GitHub Actions (they only run the sanity tests). So maybe there's an internal CI you are using for the integration tests?

About the `obsolete` directory: why not remove it in this case?

Also, it would be good to release a new version 1.0.1 after removing the obsolete files which also includes the cleanup from #21.

**Comment by Vaishnavi-infoblox** [comment]
Hi @felixfontein,

Generally when we upload collection to Galaxy there are some automated tests running. But apart from that we’re not using any separate CI testing, we have only sanity tests. And regarding obsolete directory, this can removed and a new version can be released.

**Comment by gitet** [comment]
Hi - not sure if this issue is the right place to as this, but it seems that this module collection is both included in both `community.general` and `infoblox.nios_modules` in galaxy. This is very confusing (at least to me). From which collection should I source the modules? Thx.

**Comment by felixfontein** [comment]
This is now tracked in https://github.com/ansible-collections/ansible-inclusion/discussions/11.
