### ISSUE TITLE
General question: Modules present in several collections - confusing

### ISSUE THREAD

**Issue by gitet** [infobloxopen/infoblox-ansible#26]
Hi all - I need some clarification on an issue I've run into.

I it seems that the nios_* modules are exposed both in the `community.general` and `infoblox.nios_modules` collections on galaxy. 
This is very confusing (at least to me). From which collection should I source the modules? Thanks!

**Comment by felixfontein** [comment]
The community.general versions are the modules currently included in Ansible 2.10. The idea is to switch over to this collection and include it into Ansible (see #24). Right now these modules should be mostly identical.

**Comment by gitet** [comment]
OK, thanks for the clarification!
