### ISSUE TITLE
get option on extended attr

### ISSUE THREAD

**Issue by hemskgren** [infobloxopen/infoblox-ansible#3]
Hi

I cant find an option to find/get on exttatr.

example below return network _ref from custom extattr dc_pod and dc_vlan information that we have added to networks. 
https://infoblox/wapi/v1.7/network?network_view=customer1&_return_fields%2B=extattrs&*dc_pod=1&*dc_vlan=111

From returned _ref use existing function in module.

regards
Christer

**Comment by hemskgren** [comment]
It look like i need to specify filters or network as well.

**Comment by itdependsnetworks** [comment]
You are right, I see it now. Give me a few days to address. I see another issue or two anyway.

**Comment by itdependsnetworks** [comment]
Seems this repo is now the code the new collection, and this would not be relevant
