### ISSUE TITLE
Lookup module for next available IPV6

### ISSUE THREAD

**Issue by Georgeaoun** [infobloxopen/infoblox-ansible#31]
@Vaishnavi-infoblox  Is there already a nios_next_ip and ipv6network for ipv6 lookup module somewhere already?

**Comment by badnetmask** [comment]
Maybe this: https://github.com/infobloxopen/infoblox-ansible/pull/42

**Comment by remcooverweg** [comment]
Any idea when this is going to be merged with 1.1.0 (ipv6network and ipv6host) lookup?

**Comment by anagha-infoblox** [comment]
Hi @Georgeaoun, @badnetmask, @remcooverweg,
This issue has been fixed by the following [PR](https://github.com/infobloxopen/infoblox-ansible/pull/42). It is a part of the `v1.1.1` release.
