### ISSUE TITLE
Lookup to find next host failing

### ISSUE THREAD

**Issue by sdaynjax** [infobloxopen/infoblox-ansible#46]
Running Ansible 2.10, Python: 3.6.8 Infoblox: 8.4.8

Lookup giving error.  Works when I specify the network CIDR but fails using a variable.

*****This fails:*****

  vars:
    network: 10.16.208.36/30

  collections:
    - infoblox.nios_modules

  tasks:

    - name: Obtain Creds
      include_vars: "/etc/ansible/group_vars/e-creds.yml"
      no_log: true

    - name: return next available IP address for network 10.16.208.36/30
      set_fact:
        ipaddr: "{{ lookup('nios_next_ip', network, num=1, provider=cli_infoblox ) }}"

    - name: next ip_address
      debug:
        var: ipaddr

Error:

redirecting (type: lookup) ansible.builtin.nios_next_ip to community.general.nios_next_ip
Loading collection community.general from /etc/ansible/collections/ansible_collections/community/general
fatal: [10.62.232.22]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'nios_next_ip'. Error was a <class 'ansible.errors.AnsibleError'>, original message: unable to find network object 10.16.208.36/30"
}

******This works:******

vars:
    network: 10.16.208.36/30

  collections:
    - infoblox.nios_modules

  tasks:

    - name: Obtain Creds
      include_vars: "/etc/ansible/group_vars/e-creds.yml"
      no_log: true

    - name: return next available IP address for network 10.16.208.26/30
      set_fact:
        ipaddr: "{{ lookup('nios_next_ip', 10.16.208.36/30, num=1, provider=cli_infoblox ) }}"

    - name: next ip_address
      debug:
        var: ipaddr

**Comment by badnetmask** [comment]
I don't know if this was a copy paste error, but it seems like you're defining the variable "network" with the value "10.1.1.1/30", which is an actual IP, not a network, then later you query for "1.1.1.0/30" which is indeed a network, so you do get a response. Sorry if I am missing something, but I would double check the value of the playbook variable.

**Comment by sdaynjax** [comment]
No sorry that was a typo.  The network is 10.1.1.0/30.

**Comment by badnetmask** [comment]
Doesn't matter what I do, I am unable to reproduce your error. I copy/paste your playbook, the only difference is how I pass the credentials.

I have seen people in my team having issues with Ansible due to broken Python on their side, and starting a fresh venv helped them. Have you tried that same playbook on a fresh/new venv?

**Comment by sdaynjax** [comment]
This is a new venv.  What version of Ansible and python did you test with?  I also use this same venv for all my F5, cisco and arista changes with no issue.

**Comment by badnetmask** [comment]
I tested on a venv with:
ansible 2.10.7
python 3.9.2
infoblox-client 0.5.0

The Infoblox device runs NIOS 8.5.3.

I have many other playbooks using various Infoblox modules, including the one you reported, no problems with them.

**Comment by sdaynjax** [comment]
Is interesting that it runs fine with a single variable listed for the loop. It’s only when I run it with multiple loop variables that it fails.

**Comment by badnetmask** [comment]
Is this related to #48 ?

**Comment by sdaynjax** [comment]
yes. the lookup and the lookup is working now.
