### ISSUE TITLE
Unprivileged become user would be unable to read the file

### ISSUE THREAD

**Issue by mahmoudmkh** [infobloxopen/infoblox-ansible#47]
hi,

I have this erreor message when I execute this playbook .

playbook a record :

---
- hosts: nios
  vars:
    provider:
      host: 10.200.1.50
      username: xxxxx
      password: xxxxx
      # wapi_version: "v2.1"
  connection: local
  tasks:
  - name: Create Nios A record
    nios_a_record:
      name: 1.iac.local
      ipv4: 172.30.6.1
      state: present
      comment: Created with Ansible
      state: present
      provider: "{{ provider }}"

Error message:
fatal: [10.200.1.50]: FAILED! => {"msg": "Failed to change ownership of the temporary files Ansible needs to create despite connecting as a privileged user. Unprivileged become user would be unable to read the file."}

Could you please help me to fix this issue . Thx.

BR//

**Comment by badnetmask** [comment]
That sounds more like an actual Ansible bug than anything specifically related to the Infoblox collection. Have you tried running in verbose mode?

**Comment by mahmoudmkh** [comment]
ansible-playbook test-record-A.yaml -vvvv
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: While constructing a mapping from /etc/ansible/test-record-A.yaml, line 16, column 7, found a duplicate dict key (state). Using last defined value only.
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: test-record-A.yaml ***********************************************************************************************************************************************
Positional arguments: test-record-A.yaml
verbosity: 4
connection: smart
timeout: 10
become: True
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in test-record-A.yaml

PLAY [nios] ****************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
task path: /etc/ansible/test-record-A.yaml:2
<10.200.1.50> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.200.1.50> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.200.1.50> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp/ansible-tmp-1616169060.4782057-57116097495460 `" && echo ansible-tmp-1616169060.4782057-57116097495460="` echo /var/tmp/ansible-tmp-1616169060.4782057-57116097495460 `" ) && sleep 0'
<10.200.1.50> Attempting python interpreter discovery
<10.200.1.50> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.200.1.50> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
<10.200.1.50> PUT /root/.ansible/tmp/ansible-local-4978k2awvo19/tmp0e3wberf TO /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/AnsiballZ_setup.py
<10.200.1.50> EXEC /bin/sh -c 'setfacl -m u:cd_ci_api:r-x /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/ /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/AnsiballZ_setup.py && sleep 0'
<10.200.1.50> EXEC /bin/sh -c 'chmod u+x /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/ /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/AnsiballZ_setup.py && sleep 0'
<10.200.1.50> EXEC /bin/sh -c 'chown cd_ci_api /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/ /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/AnsiballZ_setup.py && sleep 0'
<10.200.1.50> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1616169060.4782057-57116097495460/ > /dev/null 2>&1 && sleep 0'
fatal: [10.200.1.50]: FAILED! => {
    "msg": "Failed to change ownership of the temporary files Ansible needs to create despite connecting as a privileged user. Unprivileged become user would be unable to read the file."
}

PLAY RECAP *****************************************************************************************************************************************************************
10.200.1.50              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by badnetmask** [comment]
Our output proves this has definitely nothing to do with Infoblox. The error happens during gathering facts phase, which is still part of the basic Ansible execution.
Also, based on the steps, sounds like the chown/rm command combination is not really doing what it's supposed to do, so I would bet is more like a OS problem than even Ansible problem.
Anyway, not an Infoblox bug, for sure.

**Comment by mahmoudmkh** [comment]
Do you mean my os client from where i execute the playbook ? do you have any recommandation about os distribution.
Thanks.

BR//
