### ISSUE TITLE
Modules do not work with ansible-core 2.11

### ISSUE THREAD

**Issue by felixfontein** [infobloxopen/infoblox-ansible#49]
The api.py module_utils uses the private `AnsibleModule._check_type_dict` which has been removed in ansible-core's devel branch (https://github.com/ansible/ansible/pull/73703, see also https://github.com/ansible/ansible/issues/73983). This will be part of ansible-core 2.11.

See ansible-collections/community.general#2057 for a fix for this in community.general (should work with Ansible 2.9 and newer, might not work with Ansible 2.8 - I haven't checked since community.general does not support 2.8).

**Comment by anagha-infoblox** [comment]
Thank you for the fix. We have made the changes accordingly.
