### ISSUE TITLE
Help - Getting an error, running every module

### ISSUE THREAD

**Issue by alexandregoncalves17** [infobloxopen/infoblox-ansible#67]
Versions:
nios = 8.5
ansible = ansible [core 2.11.3]
Python = 3.9.2
pip Infoblox-client = 0.5.0

I am running a simple playbook:

![Screenshot 2021-08-05 at 15 25 11](https://user-images.githubusercontent.com/78537912/128366790-df9ce6e3-6173-4c99-a5de-596c8468b94e.png)

And I get this error:

![Screenshot 2021-08-05 at 15 20 05](https://user-images.githubusercontent.com/78537912/128366855-28fb49f9-247b-4499-9212-9b44201a62fc.png)

Can you help me, please?

**Comment by badnetmask** [comment]
Looks like you might be running an older version of the NIOS Ansible module, because this has already been fixed [a while ago](https://github.com/infobloxopen/infoblox-ansible/commit/aeb9cf4b1903316251596e8b4311da3c2538e26c).

**Comment by alexandregoncalves17** [comment]
> Looks like you might be running an older version of the NIOS Ansible module, because this has already been fixed [a while ago](https://github.com/infobloxopen/infoblox-ansible/commit/aeb9cf4b1903316251596e8b4311da3c2538e26c).

I created this code today, installed everything today, but I really don't know how to check the version of NIOS ansible module.

**Comment by alexandregoncalves17** [comment]
> Looks like you might be running an older version of the NIOS Ansible module, because this has already been fixed [a while ago](https://github.com/infobloxopen/infoblox-ansible/commit/aeb9cf4b1903316251596e8b4311da3c2538e26c).

![Screenshot 2021-08-05 at 15 53 46](https://user-images.githubusercontent.com/78537912/128371489-0ce7fc23-f7f0-4541-85fa-01c3c25500b4.png)

**Comment by badnetmask** [comment]
Interesting... The code in galaxy.ansible.com does not match the code here in this repo, there might be something wrong there.
I'm not part of the maintainers team, just a contributor, so I'll tag @anagha-infoblox here to take a look.
Sorry I can't help further.

In the meantime, you might want to do a direct git pull from GitHub, or downgrade your Ansible to 2.10, whatever is more convenient to you.

**Comment by alexandregoncalves17** [comment]
> Interesting... The code in galaxy.ansible.com does not match the code here in this repo, there might be something wrong there.
> I'm not part of the maintainers team, just a contributor, so I'll tag @anagha-infoblox here to take a look.
> Sorry I can't help further.
> 
> In the meantime, you might want to do a direct git pull from GitHub, or downgrade your Ansible to 2.10, whatever is more convenient to you.

Very thanks for your help! I will pul from GitHub and wait for Anagha.

**Comment by anagha-infoblox** [comment]
The problem has been fixed in the GitHub repo, and it has not been published to galaxy.ansible.com yet. In galaxy.ansible.com support is provided only for Python 2.x. We will be publishing this in our next release(last week of August). As of now, please pull the code from the GitHub repository. Sorry for the confusion.

**Comment by alexandregoncalves17** [comment]
> The problem has been fixed in the GitHub repo, and it has not been published to galaxy.ansible.com yet. In galaxy.ansible.com support is provided only for Python 2.x. We will be publishing this in our next release(last week of August). As of now, please pull the code from the GitHub repository. Sorry for the confusion.

Thanks for your answer!

I was trying to install it with this command:

 - ansible-galaxy collection install git+https://github.com/infobloxopen/infoblox-ansible.git

Tried to do via requirements file too, but not working. I'm new to ansible, do you know a way to help me ?

**Comment by anagha-infoblox** [comment]
> > The problem has been fixed in the GitHub repo, and it has not been published to galaxy.ansible.com yet. In galaxy.ansible.com support is provided only for Python 2.x. We will be publishing this in our next release(last week of August). As of now, please pull the code from the GitHub repository. Sorry for the confusion.
> 
> Thanks for your answer!
> 
> I was trying to install it with this command:
> 
> * ansible-galaxy collection install git+https://github.com/infobloxopen/infoblox-ansible.git
> 
> Tried to do via requirements file too, but not working. I'm new to ansible, do you know a way to help me ?

Following are the steps:
	1. git clone https://github.com/infobloxopen/infoblox-ansible.git
	2. **cd infoblox-ansible**(or the path where repository is cloned).
	3. **cd infoblox-ansible/ansible_collections/infoblox/nios_modules/** (or the path where the repository is cloned
	4. After getting into the appropriate folder, the following command has to be executed: **ansible-galaxy collection build**. This generates a .tar file - “﻿infoblox-nios_modules-1.1.0.tar.gz”.
	5. **cd** – change directory to the home, followed by the command **cd .ansible**
	6. The following command has to be executed in order to install the collection **ansible-galaxy collection install <collection-name>.tar.gz -p ./collections** 
Note: Provide the full path of the collection name(like /home/user/infoblox-ansible/ansible_collections/infoblox/nios_modules/infoblox-nios_modules-1.1.0.tar.gz)

Hope this helps you.

**Comment by badnetmask** [comment]
Easy way:
```
ansible-galaxy collection install git+https://github.com/infobloxopen/infoblox-ansible.git#ansible_collections/infoblox/nios_modules
```

**Comment by alexandregoncalves17** [comment]
Very thank you guys!

**Comment by anagha-infoblox** [comment]
Hi @alexandregoncalves17,
A new release is made on the [Ansible Galaxy](https://galaxy.ansible.com/infoblox/nios_modules) which fixes this issue. Please install the latest version.
