### ISSUE TITLE
Error - Dictionary Issues

### ISSUE THREAD

**Issue by alexandregoncalves17** [infobloxopen/infoblox-ansible#68]
Hello,

I have simple playbook that creates members on grid which loops a variable.
When I run the playbook, it will create the first members of the dictionary, that only change IPs, but when it reaches to the HA members for example, gives me an error.

Output:

![Screenshot 2021-08-05 at 10 59 35](https://user-images.githubusercontent.com/78537912/129016567-8ec439f1-eaa4-4639-8b02-8f7ca474f83d.png)

Playbook:

![Screenshot 2021-08-11 at 11 45 06](https://user-images.githubusercontent.com/78537912/129016786-b52be069-9988-42aa-81ab-52bec5ccd8a0.png)

Note:
     - My code works on deprecated modules of community general collection.

**Comment by anagha-infoblox** [comment]
Hi @alexandregoncalves17,
The fix for this issue is provided in the "develop" branch. We'll be merging into master before release.

**Comment by anagha-infoblox** [comment]
Hi @alexandregoncalves17,
This issue is fixed by the new release `v1.1.1`.

**Comment by alexandregoncalves17** [comment]
> Hi @alexandregoncalves17,
> This issue is fixed by the new release `v1.1.1`.

Thanks!
