### ISSUE TITLE
No collection (yet). Tidy up Repo

### ISSUE THREAD

**Issue by gundalow** [infobloxopen/infoblox-ansible#7]
Hi,

I'm part of the Community Team at Ansible. 

1) I don't see this collection at https://galaxy.ansible.com/infoblox
What's your ETA on having a `0.1.0` published?

2) No `galaxy.yml`

3) You can delete https://github.com/infobloxopen/infoblox-ansible/blob/master/.github/BOTMETA.yml

4) `tests/` directory should be `ansible_collection/infoblox/nios_modules/tests`

5) CI not running. I'll link to a template once you've done 4

6) There are existing NIOS PRs in `community.general` which need closing and directing people here https://github.com/ansible-collections/community.general/pulls?q=is%3Apr+is%3Aopen+nios

7) NIOS modules, plugins and tests need removing from https://github.com/ansible-collections/community.general/ **needs doing by 2020-07-05**
PR1 from https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration

8) All `nios` entries in https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml need updating to point to this collection. That PR once merged needs backporting to `stable-2.10` **needs doing by 2020-07-05**
PR3 from https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration

**Comment by gundalow** [comment]
@itdependsnetworks @Vaishnavi-infoblox  @sganesh-infoblox Hi I would welcome your views on this.

**Comment by gundalow** [comment]
Before deleting the content from `community.general` you need to do a file level diff, as there have been updates made by the community to that repo that may not be in this repo.

**Comment by Vaishnavi-infoblox** [comment]
Hi John,

I have few queries on the above mentioned tasks.

•	There are existing NIOS PRs in community.general which need closing and directing people here https://github.com/ansible-collections/community.general/pulls?q=is%3Apr+is%3Aopen+nios
              **Do we have to redirect them to raise these PR in our repo or Redhat has some other plan?**
 
•	tests/ directory should be ansible_collection/infoblox/nios_modules/tests – 
**Should I move /infoblox-ansible/tests to /infoblox-ansible/ansible_collection/infoblox/nios_modules?
Because this tests directory is not related to ansible-collections.**
 
•	All nios entries in https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml need updating to point to this collection. That PR once merged needs backporting to stable-2.10 needs doing by 2020-07-05
PR3 from https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration - I don't have much clarity on this. Could you please brief us on this.

**Comment by gundalow** [comment]
@Vaishnavi-infoblox Hi,
I'd start by creating a new PR which
1) Created `.github/workflows/ansible-test.yml` based on 
Add sanity tests section https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml#L7-L61
Given you already have the collection in the right subdirectory I believe you can delete https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml#L44-L45


2) If some sanity tests fail, add the `ignore-2.y.txt` files from https://github.com/infobloxopen/infoblox-ansible/tree/master/tests into `ansible_collection/infoblox/nios_modules/tests/sanity`

**Comment by gundalow** [comment]
Once you have CI working in this repo, you can ask people to move their PRs across.

**Comment by gundalow** [comment]
Looks like GitHub actions aren't enable for this repo, see https://github.com/infobloxopen/infoblox-ansible/pull/10

**Comment by gundalow** [comment]
Some notes from todays chat

1) Get CI working
2) Add `galaxy.yml`
3) Ansible-2.10 will continue to include the modules from `community.general` collection
4) Ansible-2.11 will include the NIOS modules from this collection
5) When `git rm` from community.general https://github.com/ansible/community/issues/539#issuecomment-656098926 needs doing

**Comment by anshulbehl** [comment]
@Vaishnavi-infoblox @saileshgiri 
The pull request mentioned above by @gundalow https://github.com/infobloxopen/infoblox-ansible/pull/10 should work if the Github actions are enabled on this repo
This pull request should have everything needed to run CI on the codebase using `ansible-test`

Can you check again if Guthub Actions is enabled?

**Comment by saileshgiri** [comment]
Hi @gundalow @anshulbehl , I see that GitHub actions are enabled for this repo. The "Enable local and third party Actions for this repository" button is checked. Pls see this screenshot:
![image](https://user-images.githubusercontent.com/37286784/89519635-4b19cf80-d7fa-11ea-9264-a51f1ba51d70.png)

Is there anything else I should do? If not, I think I can go ahead and merge the PR that John has raised. Pls let me know

**Comment by anshulbehl** [comment]
@gundalow Can you check the last comment?

**Comment by Vaishnavi-infoblox** [comment]
Hi @gundalow , @anshulbehl ,

I have merged the CI PR and fixed most of the pep8 issues. 
But there are 3 errors left to fix, could you please help me out in letting me know what changes are necessary next.

Please have a look that the Sanity test results-[( https://github.com/infobloxopen/infoblox-ansible/runs/983814625)]

**Comment by felixfontein** [comment]
`ERROR! lookup infoblox.nios_modules.nios_lookup missing documentation (or could not parse documentation): unknown doc_fragment(s) in file /root/ansible_collections/infoblox/nios_modules/plugins/lookup/nios_lookup.py: community.general.nios`

`ansible.errors.AnsibleError: unknown doc_fragment(s) in file plugins/modules/nios_a_record.py: nios`

These both show that there's something wrong with the doc_fragments.
1. You do not include a doc_fragment in this collection. You have to, it needs to be in `plugins/doc_fragments`. I guess you should simply copy this file: https://github.com/ansible-collections/community.general/blob/main/plugins/doc_fragments/nios.py
2. You currently use `extends_documentation_fragment: community.general.nios` and `extends_documentation_fragment: nios` in the lookup plugins and modules. You need to replace it with `extends_documentation_fragment: infoblox.nios_modules.nios`.

**Comment by Vaishnavi-infoblox** [comment]
Hi @felixfontein,

1. I added doc_fragments directory and put in nios.py in the same directory(/infoblox-ansible/ansible_collections/infoblox/nios_modules/plugins/doc_fragments).

2. Replaced extends_documentation_fragment: community.general.nios and extends_documentation_fragment: nios with extends_documentation_fragment: infoblox.nios_modules.nios in all the lookup plugins and modules but it has created 33 new issues. May be there is something wrong in whatever I have replaced.

Could you please check and let me know. This is the new sanity test results - https://github.com/infobloxopen/infoblox-ansible/runs/1001938730 and this is the latest code https://github.com/infobloxopen/infoblox-ansible/tree/ci_errors.

**Comment by felixfontein** [comment]
ansible-doc crashes on the nios_lookup lookup because the RETURNS docs are wrongly formatted: in
```
RETURN = """
obj_type:
  description:
    - The object type specified in the terms argument
  returned: always
  type: complex
  contains:
    obj_field:
      - One or more obj_type fields as specified by return_fields argument or
        the default set of fields as per the object type
"""
```
the last lines should be
```
  contains:
    obj_field:
      description:
      - One or more obj_type fields as specified by return_fields argument or
        the default set of fields as per the object type
```
(Note the added description.)

The remaining errors are mismatches between documentation and argument_spec. They probably have been there in ansible/ansible already, but were ignored. It's better to fix them. You can find the error codes explained here: https://docs.ansible.com/ansible/devel/dev_guide/testing_validate-modules.html#codes

**Comment by Vaishnavi-infoblox** [comment]
Hi @gundalow , @anshulbehl , @felixfontein,

Is there an easy technique to fix all these 943 errors - https://github.com/infobloxopen/infoblox-ansible/runs/1006601649

**Comment by felixfontein** [comment]
@Vaishnavi-infoblox if https://github.com/infobloxopen/infoblox-ansible/compare/latest_ci_errors is your current branch, then **a lot** of these errors come because you removed the docs fragment from the modules/plugins. You need to add the correct values, but not remove them.

(Also I'm not related to RedHat.)

**Comment by anshulbehl** [comment]
Please take a look at the pull request here:
https://github.com/infobloxopen/infoblox-ansible/pull/12
