### ISSUE TITLE
Examples for lookups don't work as written

### ISSUE THREAD

**Issue by mhuot** [infobloxopen/infoblox-ansible#72]
example shows --

host: "{{ lookup('infoblox.nios_modules.nios', 'record:host', filter={'name': 'hostname.ansible.com'}) }}"

What worked was --

host: "{{ lookup('infoblox.nios_modules.nios_lookup', 'record:host', filter={'name': 'hostname.ansible.com'}) }}"

**Comment by anagha-infoblox** [comment]
Hi @mhuot,
The appropriate changes have been made in the examples section of the lookup module. It is a part of the `v1.1.1` release.
