### ISSUE TITLE
nios_ptr_record does not add record to second view

### ISSUE THREAD

**Issue by cary-calpers** [infobloxopen/infoblox-ansible#95]
infoblox.nios version 1.1.12
ansible 2.9.13

Running a playbook to add a ptr record to two different views in infoblox does not add the second record even though the ansible output shows a successful change of both tasks.  A search in the infoblox UI shows only the first PTR record.  When I run the the playbook to remove the PTR records, the playbook removes one record and shows a green "no-change" for the second PTR record.

  - name: manage a PTR record from the system
    infoblox.nios_modules.nios_ptr_record:
      view: "{{ item }}"
      ptrdname: "{{ _server_fqdn }}"
      ipv4addr: "{{ _ipaddress }}"
      state: "{{ _provision_state }}"
      provider: "{{ nios_provider }}"

**Comment by anagha-infoblox** [comment]
Hi @cary-calpers,

The issue has been fixed by the following [Pull Request](https://github.com/infobloxopen/infoblox-ansible/pull/103). Hence, closing the issue.
